### ISSUE TITLE
Edit file in place

### ISSUE THREAD

**Issue by langston-barrett** [mihaimaruseac/hindent#384]
Both the venerable `sed` and `stylish-haskell` provide the `-i` flag for inplace editing of files, even though they are used by default in the "pipeline" style. It would be convenient if this package did as well! Of course, this is just an idea I'm throwing out there so feel free to close this issue if you're not interested in this feature.

**Comment by lwm** [comment]
INTERESTED. Did you get anywhere with this @siddharthist?

**Comment by tmiasko** [comment]
FYI, editing files in place is the default behaviour of hindent when file path is provided as an argument (as opposed to stdin redirection).

**Comment by toku-sa-n** [comment]
`hindent foo.hs` formats `foo.hs` in-place.
