### ISSUE TITLE
Turning on HIndent for the whole project is a a bit boilerplatey…

### ISSUE THREAD

**Issue by michalrus** [mihaimaruseac/hindent#404]
The idea here is taken from http://taylor.fausak.me/2014/03/04/haskeleton-a-haskell-project-skeleton/ — `stack test` doing formatting.

This is a working config:

* https://github.com/michalrus/kornel/blob/a7b83ae66de79d83ff08eba6428b723d002b3edb/test/HIndent_.hs#L18-L49
* https://github.com/michalrus/kornel/blob/a7b83ae66de79d83ff08eba6428b723d002b3edb/kornel.cabal#L87-L98

… which is quite a lot of code, when compared to doing the same for, say, HLint:

* https://github.com/michalrus/kornel/blob/a7b83ae66de79d83ff08eba6428b723d002b3edb/test/HLint_.hs

Also, this `format` function @ L32 is straight copy-paste from HIndent’s `Main.main`.

Maybe HIndent could extract and export this fragment of its `Main.main` for similar reuse? :smiley_cat:

**Comment by sighingnow** [comment]
Thanks for your suggestion, I will investigate this idea as soon as possible.
