### ISSUE TITLE
{-# SCC #-} pragmas break hindent

### ISSUE THREAD

**Issue by ocharles** [mihaimaruseac/hindent#408]

**Comment by sighingnow** [comment]
Could you provide any more detailed information about this issue? A minimal case that can be used to reproduce this issue, for example.

**Comment by ocharles** [comment]
```haskell
hello = {-# SCC hello #-} 42
```

Should be enough to break it.

**Comment by sighingnow** [comment]
Thanks, I will investigate this example as soon as possible.

**Comment by sighingnow** [comment]
@ocharles  It seems a bug from HSE. If you don't omit the double quotes(see https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/profiling.html#inserting-cost-centres-by-hand) it will works well. Please try

~~~haskell
hello = {-# SCC "hello" #-} 42
~~~

**Comment by toku-sa-n** [comment]
Closing as the current master can handle SCC pragmas.
