### ISSUE TITLE
Hindent breaks TH typed expression splicing: ( $$() syntax )

### ISSUE THREAD

**Issue by utdemir** [mihaimaruseac/hindent#425]
Correct syntax:

```
{-# LANGUAGE TemplateHaskell #-}
main = $$(error "foo")
```

Hindent gives: `Parse error: $$`

----

Also on some cases it mixes them up with infix operators:

From: 

```
{-# LANGUAGE TemplateHaskell #-}
main = print $$(error "foo")
```

After hindent: 

```
{-# LANGUAGE TemplateHaskell #-}
main = print $$ (error "foo")
```

Note that now the meaning is changed (now `$$` is parsed as an operator).

**Comment by sighingnow** [comment]
Thanks for your report. It's indeed a HSE's bug. See also haskell-suite/haskell-src-exts#278.

**Comment by toku-sa-n** [comment]
Closing as the current master no longer has this bug.
