### ISSUE TITLE
Indenting class creates syntax error

### ISSUE THREAD

**Issue by lorenzo** [mihaimaruseac/hindent#433]
Trying to indent this snippet

```haskell
-- | Foo
class GToJSON enc arity f where
    -- | Bar
  gToJSON :: Options -> ToArgs enc arity a -> f a -> enc
```

Produces 

```haskell
-- | Foo
class GToJSON enc arity f
    -- | Bar
  | 
  where
  gToJSON :: Options -> ToArgs enc arity a -> f a -> enc
```

Which makes the code not compile anymore.

**Comment by lorenzo** [comment]
The error appears after the commit https://github.com/commercialhaskell/hindent/commit/f20fee27cb6d936bd6a5d2b796ae060e0044ebf2

**Comment by sighingnow** [comment]
Thanks for your reporting!

**Comment by NorfairKing** [comment]
+1

**Comment by toku-sa-n** [comment]
Closing as the current master formats the input correctly.
