### ISSUE TITLE
Negative literals mangled

### ISSUE THREAD

**Issue by koterpillar** [mihaimaruseac/hindent#445]
```
{-#LANGUAGE NegativeLiterals #-}

data Pair = Pair Int Int

val :: Pair
val = Pair 5 -6
```

This is valid and parsed as `Pair 5 (-6)`, but hindent changes the line to:

```
val = Pair 5 - 6
```

which gets parsed as `Pair (5 - 6)` and is invalid.

**Comment by sighingnow** [comment]
Thanks for your report.

**Comment by sighingnow** [comment]
I'm afraid that the `NegativeLiterals` extension isn't supported by haskell-src-exts. All known extensions for HSE [are listed here](http://hackage.haskell.org/package/haskell-src-exts-1.19.1/docs/Language-Haskell-Exts-Extension.html#t:KnownExtension).

**Comment by toku-sa-n** [comment]
Closing as the current master doesn't have this bug anymore.
