### ISSUE TITLE
Inconsistent off-alignment placing of "do" and "let" blocks

### ISSUE THREAD

**Issue by AshleyYakeley** [mihaimaruseac/hindent#462]
Sometimes `hindent` does this:
```
foo = do
    expr1
    expr2
````
And sometimes it does this:
```
foo =
    do expr1
       expr2
```

The former layout matches [the official style](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md) and keeps things aligned at multiple of 4 spaces (if that's what the user has specified). The latter layout introduces a non-4-space alignment and is unexpected. There's a similar issue with `let`.

Both `do` and `let` should consistently match the style guide and place the keyword on the same line, and keep all blocks 4-space (or 2-space) aligned:
```
foo = do
    expr1
    expr2

bar = let
    val1 = expr1
    val2 = expr2
    in expr
```

**Comment by sighingnow** [comment]
I agree that we should fix the inconsistency in `do` and format `do` statement as

~~~haskell
foo = do
    expr1
    expr2
~~~

I also the inconsistent behavior of `let ... in` should be fixed but I think the layout

~~~ghc
bar = let
    val1 = expr1
    val2 = expr2
    in expr
~~~

looks a bit strange. The Johan Tibell style don't provide example for `let ... in` and I think the following layout is more common in practical Haskell code:

~~~haskell
bar = let val1 = expr1
          val2 = expr2
       in expr
~~~

or

~~~haskell
bar =
  let val1 = expr1
      val2 = expr2
   in expr
~~~

**Comment by AshleyYakeley** [comment]
It seems to me `let` and `do` should behave the same way, for consistency?
