### ISSUE TITLE
Qualified multiplication gets mangled

### ISSUE THREAD

**Issue by tfausak** [mihaimaruseac/hindent#465]
Given this input:

``` hs
good = 2 Prelude.+ 3

bad = 2 Prelude.* 3
```

`hindent` 5.2.4.1 produces this output:

``` hs
good = 2 Prelude.+ 3

bad = 2 Prelude .* 3
```

This is obviously incorrect and fails with a couple errors:

```
Example.hs:3:9: error: Data constructor not in scope: Prelude
  |
3 | bad = 2 Prelude .* 3
  |         ^^^^^^^

Example.hs:3:17: error:
    • Variable not in scope: (.*) :: t0 -> Integer -> t
    • Perhaps you meant one of these:
        ‘.’ (imported from Prelude), ‘*’ (imported from Prelude),
        ‘<*’ (imported from Prelude)
  |
3 | bad = 2 Prelude .* 3
  |                 ^^
```

**Comment by sighingnow** [comment]
Strange bug, thanks for your report!

**Comment by sighingnow** [comment]
Seems a HSE's bug, HSE has parsed `Prelude.*` as `Prelude` and `.*`, not `Prelude` and `*`.

**Comment by sighingnow** [comment]
Current HSE has a bug that extension `KindSignatures` would breaking qualified multiplication operators. See haskell-suite/haskell-src-exts#384.

**Comment by sighingnow** [comment]
As well as `PolyKinds`, `TypeFamilies`, `TypeFamilyDependences`.

**Comment by toku-sa-n** [comment]
Closing as the current master formats the input correctly.
