### ISSUE TITLE
Lambda+BangPatterns+do -> syntax error

### ISSUE THREAD

**Issue by lehins** [mihaimaruseac/hindent#494]
Whenever there is a lambda with it's first argument being strict (bang pattern), and the body of a lambda function starts with a `do`, hindent removes a space between lambda and an argument resulting in code that doesn't compile.

Example that works:

```
foo = \ !x ->
  print x
```
Formats into:
```
foo = \ !x -> print x
```

All is good. Now below we add a `do`:

```
foo = \ !x -> do
  print x
```
Formats into:
```
foo = \!x -> do print x
```

Which no longer compiles, since it's a parse error: `\!x`

Cheers.  :)

**Comment by toku-sa-n** [comment]
Closing as the current master no longer has this bug.
