### ISSUE TITLE
Arrow syntax produces invalid syntax

### ISSUE THREAD

**Issue by MDeiml** [mihaimaruseac/hindent#501]
When using arrow syntax in a where block hindent produces invalid syntax:
```haskell
  where
    w =
        proc ~(last, config) -> do
     let ~(content', caret', caret0')
           = maybe last (\ s -> (s, length s, length s)) ev
```
looks like 
```haskell
  where
    w =
        proc ~(last, config) ->
  do let ~(content', caret', caret0')
           = maybe last (\ s -> (s, length s, length s)) ev
```
after reformatting.

**Comment by turion** [comment]
This is the bug that keeps me from adopting hindent

**Comment by chrisdone** [comment]
> This is the bug that keeps me from adopting hindent

Nobody is stopping you from going fixing it. Are you a Haskeller or not?

**Comment by turion** [comment]
That's quite a condescending answer. How would you know whether I know enough Haskell to contribute, and have enough time to do so? In fact I'm looking at the source code right now to see whether I can fix it, but it's not so obvious if you've never seen the hindent source before.

**Comment by chrisdone** [comment]
I must have misunderstood the tone of your original comment, my apologies.

**Comment by turion** [comment]
Thanks. I'd like to apologize as well, it was too easy to misunderstand my comment as "Fix this bug ASAP! For free!". I should have taken the extra minute to write "Just to let you know, I'm one more person affected by this bug. I'd like to use hindent, but this here is a blocker, because indeed there are people who use arcane language extensions such as `Arrows`.".

**Comment by toku-sa-n** [comment]
Not sure what's the desired format here, but the current master formats the below code

```haskell
{-# LANGUAGE Arrows  #-}

foo=undefined
  where
    w =
        proc ~(last, config) -> do
     let ~(content', caret', caret0')
           = maybe last (\ s -> (s, length s, length s)) ev
```

to

```haskell
{-# LANGUAGE Arrows #-}

foo = undefined
  where
    w =
      proc ~(last, config) -> do
        let ~(content', caret', caret0') =
              maybe last (\s -> (s, length s, length s)) ev
```

At least the result code doesn't cause a parse error.

**Comment by toku-sa-n** [comment]
Closing as this bug seems to be fixed. Feel free to reopen this issue if it's not fixed.
