### ISSUE TITLE
Comments sometimes lost/deleted or misplaced (before/after where/let/do/=/etc)

### ISSUE THREAD

**Issue by chrisdone** [mihaimaruseac/hindent#511]
Creating this issue as a catch-all for the comment handling situation in hindent. Redirect all issues here.

Time to fix this once and for all.

**Comment by gasi** [comment]
Hi. First of all, `hindent` is great — thank you!

I ran into https://github.com/commercialhaskell/hindent/issues/455 and was wondering if we should repost examples here since the original is closed or is this just a catch-all issue for all the others?

**Comment by toku-sa-n** [comment]
For those who found new cases: please open a new issue with minimum input to reproduce, expected output, and the actual output. Thank you.
