### ISSUE TITLE
DerivingVia gives syntax errors for valid code

### ISSUE THREAD

**Issue by kozross** [mihaimaruseac/hindent#523]
## Problem

Suppose we have this code:

```haskell
newtype Trit = Trit (Maybe Bool)
    deriving Eq via (Maybe Bool)
```

GHC will compile this code just fine, but hindent complains that there's a parse error on 'via'.

- [X] I checked the issue tracker for existing issues about this problem.
- [X] I'm using the latest version of hindent.

**Comment by kozross** [comment]
This appears to be an [issue upstream with haskell-src-exts][1].

[1]: https://github.com/haskell-suite/haskell-src-exts/issues/419

**Comment by domenkozar** [comment]
FYI: https://github.com/ennocramer/floskell (fork of hindent) seems to support derivingvia.

**Comment by toku-sa-n** [comment]
Closing as the current master can format the code.
