### ISSUE TITLE
CPP breaks hindent on ``vector-sized``

### ISSUE THREAD

**Issue by kozross** [mihaimaruseac/hindent#525]
## Problem

When I attempt to execute ``hindent`` on [this file of ``vector-sized``][1], I get this:

```
hindent: src/Data/Vector/Generic/Mutable/Sized.hs:70:19: Parse error: EOF
CallStack (from HasCallStack):
  error, called at src/main/Main.hs:53:23 in main:Main
```

Adding ``-X CPP`` doesn't help.

- [X] I checked the issue tracker for existing issues about this problem.
- [X] I'm using the latest version of hindent.

[1]: https://github.com/expipiplus1/vector-sized/blob/master/src/Data/Vector/Generic/Mutable/Sized.hs

**Comment by toku-sa-n** [comment]
I'm sorry, but the current master no longer fails to format the file.
