### ISSUE TITLE
ANN pragma wraps too eagerly

### ISSUE THREAD

**Issue by nimiwio** [mihaimaruseac/hindent#533]
## Problem

ANN pragmas seem to wrap before the 80 character limit is reached. The below was done with a freshly installed hindent.

Input haskell
```haskell
{-# ANN type Foo (Just "Annotation that wraps somewhat strangely") #-}
```

Expected output haskell
```haskell
{-# ANN type Foo (Just "Annotation that wraps somewhat strangely") #-}
```

Actual output haskell
```haskell
{-# ANN type Foo (Just "Annotation that wraps somewhat strangely")
  #-}
```

**Comment by toku-sa-n** [comment]
Closing as the latest master doesn't have this bug anymore.
