### ISSUE TITLE
Qualified 'M.role' treated like function composition 'M . role'

### ISSUE THREAD

**Issue by ollef** [mihaimaruseac/hindent#538]
## Problem

`M.role` is not treated as a qualified name, but is instead pretty-printed as function composition. Other names, like `notRole`, don't seem to be affected.

I suppose `role` is treated differently somewhere because of `RoleAnnotations` but I don't think that should affect value expressions. It may be that this is a HSE bug.

- [x] I checked the issue tracker for existing issues about this problem.
- [x] I'm using the latest version of hindent.

Input haskell
```haskell
a = M.role

b = M.notRole
```

Expected output haskell
```haskell
a = M.role

b = M.notRole
```

Actual output haskell
```haskell
a = M . role

b = M.notRole
```

**Comment by ollef** [comment]
A workaround is to pass `-XNoRoleAnnotations`.

**Comment by toku-sa-n** [comment]
Closing as the current master no longer has this bug.
