### ISSUE TITLE
NumericUnderscores is not supported

### ISSUE THREAD

**Issue by sir4ur0n** [mihaimaruseac/hindent#542]
## Problem

Hindent doesn't seem to support `NumericUnderscores`.

- [X] I checked the issue tracker for existing issues about this problem.
- [X] I'm using the latest version of hindent. (5.2.7)

Input haskell
```haskell
{-# LANGUAGE NumericUnderscores #-}

module Foo where

foo = 10_000
```

Expected output haskell
```haskell
{-# LANGUAGE NumericUnderscores #-}

module Foo where

foo = 10_000
```

Actual output haskell
```haskell
{-# LANGUAGE NumericUnderscores #-}

module Foo where

foo = 10 _000
```
Note the space between `10` and `_000`.

Also doesn't work when the extension is enabled in Stack `package.yaml`.

**Comment by merc1031** [comment]
I ran into a similar issue in [Floskell](https://github.com/ennocramer/floskell) and opened [Numeric Litaral Issues in HSE](https://github.com/haskell-suite/haskell-src-exts/issues/455), but it was blocking me so I submitted [HexFloatLiterals in HSE](https://github.com/haskell-suite/haskell-src-exts/pull/456) and building on it [NumericUndersores in HSE](https://github.com/haskell-suite/haskell-src-exts/pull/457).

Hoping they get merged in at some point
