### ISSUE TITLE
Reformat removes ViewPatterns extension which breaks previously working code

### ISSUE THREAD

**Issue by mnn** [mihaimaruseac/hindent#550]
## Problem

Reformat removes ViewPatterns extension pragma which breaks previously working code. Probably some interaction between TemplateHaskell and/or QuasiQuotes. Initially reported [here](https://github.com/rikvdkleij/intellij-haskell/issues/452).

- [x] I checked the issue tracker for existing issues about this problem.
- [ ] I'm using the latest version of hindent.
  - I don't know which version is being used, I am using intellij-haskell which I was told uses this tool

Input haskell
```haskell
{-# LANGUAGE ViewPatterns              #-}
...
mkYesod
  "App"
  [parseRoutes|
/categories CategoriesR GET
/categories/#Text CategoryR GET
/images/#Text ImageR GET
|]
```

Expected output haskell
```haskell
{-# LANGUAGE ViewPatterns              #-}
...
mkYesod
  "App"
  [parseRoutes|
/categories CategoriesR GET
/categories/#Text CategoryR GET
/images/#Text ImageR GET
|]
```

Actual output haskell
```haskell
...
mkYesod
  "App"
  [parseRoutes|
/categories CategoriesR GET
/categories/#Text CategoryR GET
/images/#Text ImageR GET
|]
```

**Comment by toku-sa-n** [comment]
Closing as the current master no longer has this bug.
