### ISSUE TITLE
Extension BlockArguments breaks Hindent

### ISSUE THREAD

**Issue by gsebil08** [mihaimaruseac/hindent#552]
## Problem

When adding extension `{-# LANGUAGE BlockArguments #-}` and using it by deleting useless `$` hindent is not able to reformat correctly the file

- [x] I checked the issue tracker for existing issues about this problem.
- [x] I'm using the latest version of hindent.

Input haskell
```haskell
{-# LANGUAGE BlockArguments #-}

module MyModule where

import    Data.ByteString                      as BS
import       Data.Time.Clock.POSIX                (getPOSIXTime)

foo :: [Integer] -> [Integer]
foo = fmap \i -> i+1

```

Expected output haskell
```haskell
{-# LANGUAGE BlockArguments #-}

module MyModule where

import Data.ByteString as BS
import Data.Time.Clock.POSIX (getPOSIXTime)

foo :: [Integer] -> [Integer]
foo = fmap \i -> i + 1

```

Actual output haskell
```haskell
{-# LANGUAGE BlockArguments #-}

module MyModule where

import    Data.ByteString                      as BS
import       Data.Time.Clock.POSIX                (getPOSIXTime)

foo :: [Integer] -> [Integer]
foo = fmap \i -> i+1

```

When executing in command line:
```bash
hindent src/MyModule.hs       
hindent: src/MyModule.hs:9:12: Parse error: \
CallStack (from HasCallStack):
```

```bash
hindent --version
hindent 5.3.1
```

**Comment by jimenezrick** [comment]
Seems like the usual suspect `haskell-src-exts` doesn't support this extension, very little to do here I guess: http://hackage.haskell.org/package/haskell-src-exts-1.22.0/docs/Language-Haskell-Exts-Extension.html#t:KnownExtension

**Comment by Sir4ur0n** [comment]
Now for the good news: there's a PR opened to fix this exactly: https://github.com/haskell-suite/haskell-src-exts/pull/444

I propose we keep this issue open until the PR is merged, and then Hindent upgrades its dependency of `haskell-src-exts`

**Comment by DanBurton** [comment]
The haskell-src-exts PR is merged. Please give me a couple more days to release & ping me if I forget.

**Comment by Sir4ur0n** [comment]
Ping @DanBurton any progress please? No worries if you don't have time 😄

**Comment by DanBurton** [comment]
Thanks for the bump, @Sir4ur0n. Apologies for the delay; I just uploaded `haskell-src-exts-1.23.0` which should handle block arguments as expected.

**Comment by Sir4ur0n** [comment]
No need to apologize, thank you very much!

**Comment by gsebil08** [comment]
We do not use hindent anymore, but trouble is still present.
In your stack.yaml, I still find:
`haskell-src-exts-1.20.2` looks like it has not been updated to `1.23.0`, is it normal?

**Comment by toku-sa-n** [comment]
Closing as the current master doesn't have this bug anymore.
