### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by chrisdone** [mihaimaruseac/hindent#557]
Hi all,

I'm sunsetting my maintenance of hindent. It basically does what I want and has done for the last four years. I've put enough hours into this project that I'm ready to move onto new things.

The approach of using GHC to format code is already being explored by at least two other projects:

* [brittany](http://hackage.haskell.org/package/brittany)
* [ormolu](https://github.com/tweag/ormolu)

So if you still want hindent to continue being updated, I suggest you take over as maintainer, either as a group or an individual. Feel free to comment here. I'm happy to create an organization and move the project into it.

In the absence of anyone taking over, the GitHub project will be archived on Jan 31st. By that point, the issues/PRs will be lost.

Cheers,

Chris

**Comment by mihaimaruseac** [comment]
I volunteer to maintain it

**Comment by clinty** [comment]
What's happening with this?

**Comment by chrisdone** [comment]
I'm afraid I don't know @mihaimaruseac well from the community. It's hard to hand over to someone I don't know well.

**Comment by mihaimaruseac** [comment]
Fair point. Lately I've been active only in https://github.com/commercialhaskell/stackage though I did have some contributions to Stack a few years ago and still have to work on some of the issues there. Only [one](http://hackage.haskell.org/package/io-manager) released package and I haven't continued to release more [HCAR editions](https://wiki.haskell.org/Haskell_Communities_and_Activities_Report)

**Comment by chrisdone** [comment]
@mihaimaruseac Oh, I do recognize you from stackage work. OK, I trust you with maintaining hindent. Are you open to moving the project to your name?

**Comment by mihaimaruseac** [comment]
Yes, that could work.

There is one more step I need to take now: need to make sure Google legal is not opposed to maintaining the project. Just sent an application and should get a reply in at most a week.

**Comment by mihaimaruseac** [comment]
Sorry for the delay due to 4th of July week, but now I have approval to maintain the project.

**Comment by chrisdone** [comment]
Great, thanks @mihaimaruseac. Then I'll transfer it over to you.

**Comment by mihaimaruseac** [comment]
Thank you. I'll start working on the issues
