### ISSUE TITLE
Infix constructor backticks are removed

### ISSUE THREAD

**Issue by sir4ur0n** [mihaimaruseac/hindent#560]
## Problem

Using Hindent 5.3.1
Hindent somehow removes backticks when declaring a constructor in infix (but not an operator), while [this syntax is legal according to GHC](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#infix-type-constructors-classes-and-type-variables).
> Back-quotes work as for expressions, both for type constructors and type variables; e.g. Int `Either` Bool, or Int `a` Bool. Similarly, parentheses work the same; e.g. (:*:) Int Bool.

This leads to a compilation failure: `Not a data constructor: a`

- [x] I checked the issue tracker for existing issues about this problem.
- [x] I'm using the latest version of hindent.

Input haskell
```haskell
data Foo a = a `Bar` a
```

Expected output haskell
```haskell
data Foo a =
  a `Bar` a
```

Actual output haskell
```haskell
data Foo a =
  a Bar a
```

**Comment by toku-sa-n** [comment]
Closing as the current master formats the code correctly.
