### ISSUE TITLE
Arrow syntax for hindent.el

### ISSUE THREAD

**Issue by poscat0x04** [mihaimaruseac/hindent#561]
**Completed checklist**

- [x] I've checked the issue tracker for similar issues.
- [x] I am not creating an issue about adding more configuration options for the styling/layout of hindent, because hindent is not about customizing style.

**Problem description**

hindent.el cannot deal with arrow syntax

**Comment by toku-sa-n** [comment]
The current master supports the arrow syntax, which should resolve this issue. Closing.
