### ISSUE TITLE
Hindent with Cabal

### ISSUE THREAD

**Issue by Spidy104** [mihaimaruseac/hindent#569]
## Question

Can Anyone please tell how One can install hindent with cabal?

**Comment by mihaimaruseac** [comment]
`cabal install hindent` should work. What error do you get?

**Comment by Spidy104** [comment]
It gives a weird error that some packages are redundant, cannot remember exactly...
But I cloned the repo and then I ran cabal install hindent and finally the error was fixed.

**Comment by mihaimaruseac** [comment]
The repo is slightly ahead of the published package as I'm currently working on getting `hindent` working with newer GHC.

Since you got it working, I'm thinking we can close this issue. Please reopen if there are more items to resolve

**Comment by Spidy104** [comment]
Okay No problem.. I had currently GHC 8.10.2 Which one are you developing it with?

**Comment by mihaimaruseac** [comment]
8.10.2 is the goal. The CI passes for it https://github.com/mihaimaruseac/hindent/runs/1238752532?check_suite_focus=true
