### ISSUE TITLE
Please release a new version that includes the MonadFail fix in newer GHC versions

### ISSUE THREAD

**Issue by markus1189** [mihaimaruseac/hindent#570]
## Question

Currently, `hindent` breaks in nixpkgs/nixpkgs due to the missing `MonadFail` instance for newer GHC versions.

This problem is actually already fixed thanks to https://github.com/mihaimaruseac/hindent/pull/567 , but I don't see any new version bumps and releases since then.

**Can you please release a new version of `hindent`?**

**Comment by markus1189** [comment]
Pinging @mihaimaruseac :wink:

**Comment by mihaimaruseac** [comment]
Sorry for the delay. Will try to get this in next week, currently I am overswamped with work stuff :(

**Comment by markus1189** [comment]
No worries, sounds good!  Life kind of has the tendency to get in the way :shrug:

**Comment by ixmatus** [comment]
I just ran into this myself. A new release would be lovely.

**Comment by mihaimaruseac** [comment]
Planning to do a release in the next few hours, if everything works properly.

Apologies for the extremely long delay.

**Comment by mihaimaruseac** [comment]
I need to be added to the Hackage group to upload the new package, so this will bring a little bit more delay

**Comment by mihaimaruseac** [comment]
And we have 5.3.2 released: http://hackage.haskell.org/package/hindent-5.3.2

**Comment by markus1189** [comment]
Thanks!

**Comment by ixmatus** [comment]
Thanks you!
