### ISSUE TITLE
Deletes multiline comments if there is no code 

### ISSUE THREAD

**Issue by sumanthyedoti** [mihaimaruseac/hindent#586]
i.e. when only a multiline comment exists in a file

**Comment by toku-sa-n** [comment]
The current master no longer removes comments from a comment-only source code, but it inserts extra newlines.

### MRE

#### Input

```haskell
-- foo
```

#### Output

```haskell
  
  
-- foo
```

(Note that the actual output does not have two spaces in each unnecessary blank line. It is needed to render newlines on GitHub issue)
