### ISSUE TITLE
Consider using `ghc-lib-parser` instead of `haskell-src-exts`

### ISSUE THREAD

**Issue by toku-sa-n** [mihaimaruseac/hindent#587]
**Completed checklist**

- [x] I've checked the issue tracker for similar issues.
- [x] I am not creating an issue about adding more configuration options for the styling/layout of hindent, because hindent is not about customizing style.

**Problem description**

[`haskell-src-exts`](https://hackage.haskell.org/package/haskell-src-exts) does not implement some extensions, and unfortunately, it does not seem to be maintained.

For example, we cannot use `hindent` with the [`OverloadedRecordDot`](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/overloaded_record_dot.html) extension.

`hindent app/Lib.hs` with this `.hindent.yaml` cannot convert the following code.

```haskell
{-# LANGUAGE OverloadedRecordDot #-}
data Rectangle =
  Rectangle
    { width  :: Int
    , height :: Int
    }

area :: Rectangle -> Int
area r = r.width * r.height
```

```yaml
extensions:
  - OverloadedRecordDot
```

```
% hindent app/Lib.hs
hindent: AesonException "Error in $: Unknown extension: OverloadedRecordDot"
CallStack (from HasCallStack):
  error, called at src/main/Main.hs:88:19 in main:Main
```

[`KnownExtension`](https://hackage.haskell.org/package/haskell-src-exts-1.23.1/docs/Language-Haskell-Exts-Extension.html) lacks the extension.

**Proposed solution**

I think that replacing `haskell-src-exts` with [`ghc-lib-parser`](https://hackage.haskell.org/package/ghc-lib-parser) is one of the options to solve the problem. It is maintained, and other projects (e.g., [`hlint`](https://github.com/ndmitchell/hlint) and [`stylish-haskell`](https://hackage.haskell.org/package/stylish-haskell)) use it. Also, `haskell-src-exts`' readme [suggests the use of it](https://hackage.haskell.org/package/haskell-src-exts).

**Alternatives**

Taking over the maintenance of the library is another option.

**Comment by mihaimaruseac** [comment]
Interesting. I was a little bit out of the loop, but I think it is a good idea.

**Comment by toku-sa-n** [comment]
I'm currently rewriting `hindent` with `ghc-lib-parser`. Once I complete it, I'll submit a PR.

**Comment by mihaimaruseac** [comment]
Awesome. Please CC me on the PR so it raises to the top of my notifications.

Thank you for working on it!
