### ISSUE TITLE
Unable to install with stack lts 16

### ISSUE THREAD

**Issue by uhbif19** [mihaimaruseac/hindent#589]
## Problem

Trying to install hindent-5.3.4 in stack lts 16. Getting error:

```
/tmp/stack-166f35d2e18b674f/hindent-5.3.4/src/HIndent/Pretty.hs:988:7: error:
    Not in scope: data constructor ‘TypeA’
    |
988 |       TypeA _ ty -> pretty ty
    |       ^^^^^
```

I looked at code it is: 

```
#if MIN_VERSION_haskell_src_exts(1,21,0)
      TypeA _ ty -> pretty ty
#else
```
But it looks haskell-srd-exts 1.21 does not have TypeA (https://hackage.haskell.org/package/haskell-src-exts-1.21.0/docs/Language-Haskell-Exts-Syntax.html) only 1.22 got it. So it think it meant to be another version constrait.

- [x] I checked the issue tracker for existing issues about this problem.
- [x] I'm using the latest version of hindent.

**Comment by toku-sa-n** [comment]
Sorry for the late response. Since HIndent no longer uses `haskell-src-exts`, I think this problem no longer occurs.
