### ISSUE TITLE
Fix Scorecard Github Action by upgrading to 2.0.6

### ISSUE THREAD

**Issue by joycebrum** [mihaimaruseac/hindent#604]
## Problem

@mihaimaruseac I've noticed that the Scorecard Github Action is with an error (https://github.com/mihaimaruseac/hindent/actions/runs/3347737401) that is already solved in the version 2.0.6 (https://github.com/joycebrum/hindent/actions/runs/3371376762). 

I'll open the PR to upgrade the version and, consequently, fix the error hapening in the action.

- [x] I checked the issue tracker for existing issues about this problem.
- [x] I'm using the latest version of hindent.

**Comment by mihaimaruseac** [comment]
Thank you very much. I haven't gotten a chance to get to it but it's so great you've opened this!
