### ISSUE TITLE
`TESTS.md` needs to be reorganized

### ISSUE THREAD

**Issue by toku-sa-n** [mihaimaruseac/hindent#610]
Currently, the test suite file does not have enough sections, making it difficult to read and unclear where to add a new test code. Also, the regression test section is now a jumble of various tests. Therefore, the sections should be broken up into smaller ones, and tests in the regression test section should be moved to the appropriate one.

**Comment by mihaimaruseac** [comment]
Thank you very much for all these PRs and fixing this!
