### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by toku-sa-n** [mihaimaruseac/hindent#668]
@mihaimaruseac We've done a few things. I still have the will to fix the remaining issues, but they are harder to resolve than already fixed things. Though I don't need the latest features urgently, could you release a new version here? I think it's good timing.

**Comment by mihaimaruseac** [comment]
I'm planning to do a new release by the end of the month. Want to update the CI first, I've run a few experiments over the holiday break and will land them soon, as soon as I get some time to transfer them here. After that, we can do the release. Shouldn't be after end of this month.

**Comment by toku-sa-n** [comment]
Okay, thanks. I'm looking forward to it!

**Comment by toku-sa-n** [comment]
@mihaimaruseac Kindly pinging. Is there progress, or is there anything I can do?

**Comment by amosnier** [comment]
I'm curious too, since this release should solve a bug I have reported.

**Comment by mihaimaruseac** [comment]
Apologies, missed this during the layoffs and just came back to the repo.

Trying to do it today so there won't be any more delay.

**Comment by mihaimaruseac** [comment]
Release done. Sorry for the delay.

https://hackage.haskell.org/package/hindent-6.0.0

https://github.com/mihaimaruseac/hindent/releases/tag/v6.0.0

**Comment by toku-sa-n** [comment]
Thank you, I really appreciate it!

**Comment by mihaimaruseac** [comment]
Thank you very much for all the PR work for the migration
