### ISSUE TITLE
Comments removed for no good reason?

### ISSUE THREAD

**Issue by amosnier** [mihaimaruseac/hindent#677]
## Comments removed for no good reason?

Comments seem to be removed for no good reason.

- [x] I checked the issue tracker for existing issues about this problem.
- [x] I'm using the latest version of hindent.

Input haskell
```
-- Is it removing stuff?
-- Is it just the first line?
-- What the heck is that?
```

Expected output haskell
```
-- Is it removing stuff?
-- Is it just the first line?
-- What the heck is that?
```

Actual output haskell
```

-- What the heck is that?
```

**Comment by toku-sa-n** [comment]
Thanks for the report. The current master can handle your input correctly, but it's not been released yet. You can try it by the following commands.

```sh
git clone https://github.com/mihaimaruseac/hindent
cd hindent
# Method one
stack run -- path/to/your/file.hs
# Method two
cat path/to/your/file.hs|stack run
```

I'm closing this issue as it's solved. For the new release, please see #668.
