### ISSUE TITLE
Extra space after dot in case of imports with new qualifier

### ISSUE THREAD

**Issue by alexeytochin** [mihaimaruseac/hindent#693]
## Problem

After imports with new qualifier an unnecessary space is added after dot that makes code incompilable.

Input haskell
```haskell
import qualified Prelude as P
a = 2 P.* 3
```

Expected output haskell
```haskell
import qualified Prelude as P
a = 2 P.* 3
```

Actual output haskell
```haskell
import qualified Prelude as P
a = 2 P .* 3
```

**Comment by toku-sa-n** [comment]
Thank you for the report. The latest HIndent should format your input correctly. Please try update it. The latest version is 6.0.0.
