### ISSUE TITLE
ExistentialQuantification-style context without forall is deleted

### ISSUE THREAD

**Issue by jmcarthur** [mihaimaruseac/hindent#863]
## Problem

If you use ExistentialQuantification syntax to attach constraints to a constructor, hindent removes the constraints. (It does not remove them, however, if you are using GADT syntax.)

- [X] I checked the issue tracker for existing issues about this problem.
- [X] I'm using the latest version of hindent.

Input haskell
```haskell
data Foo a = Eq a => Foo
```

Expected output haskell
```haskell
data Foo a = Eq a => Foo
```
or some whitespace-only variation

Actual output haskell
```haskell
data Foo a
  = Foo
```

**Comment by toku-sa-n** [comment]
Thanks for the report. This problem is solved in the current master. Please check it.

**Comment by jmcarthur** [comment]
It works! Thanks.
