### ISSUE TITLE
Detect {-# LANGUAGE UnboxedTuples #-} automatically

### ISSUE THREAD

**Issue by jmcarthur** [mihaimaruseac/hindent#866]
**Completed checklist**

- [X] I've checked the issue tracker for similar issues.
- [X] I am not creating an issue about adding more configuration options for the styling/layout of hindent, because hindent is not about customizing style.

**Problem description**

In https://github.com/mihaimaruseac/hindent/issues/419, it is explained that UnboxedTuples is intentionally unsupported by default because it would be mutually exclusive with handling lens operators. Makes sense, but it would be nice if this behavior would be altered by LANGUAGE pragmas so that it doesn't have to be overridden in the command manually.

**Proposed solution**

If the file contains the UnboxedTuples language extension, behave as though passing -XUnboxedTuples on the command line.

**Alternatives**

I can't think of an alternative.

**Comment by toku-sa-n** [comment]
Seems like HIndent 6.0.1 can detect the language extension. Coulo you give me an example which HIndent can't format?

Input

```haskell
{-# LANGUAGE MagicHash #-}
{-# LANGUAGE UnboxedTuples #-}

f :: (# Int, Int #) -> Int
f t = case t of
    (# x, _ #) -> x
```

Output

```haskell
{-# LANGUAGE MagicHash #-}
{-# LANGUAGE UnboxedTuples #-}

f :: (# Int, Int #) -> Int
f t =
  case t of
    (# x, _ #) -> x
```

**Comment by jmcarthur** [comment]
It works in patterns but not in expressions, so I guess it's actually a bug. Perhaps I was wrong that this has anything to do with https://github.com/mihaimaruseac/hindent/issues/419.

**Comment by toku-sa-n** [comment]
Thanks for the code. I can reproduce it, and I am fixing it now.
